export enum CatalogueTypeEnum {
    inspections_state = 'inspections_state',
    processes_state = 'processes_state',
    cadastres_state = 'cadastres_state',
    dpa_zone = 'dpa_zone',
    activities_geographic_area = 'activities_geographic_area',
    internal_zonal_users_zone = 'internal_zonal_users_zone',
    BLOOD_TYPE = 'BLOOD_TYPE',
    ETHNIC_ORIGIN = 'ETHNIC_ORIGIN',
    GENDER = 'GENDER',
    IDENTIFICATION_TYPE = 'IDENTIFICATION_TYPE',
    MARITAL_STATUS = 'MARITAL_STATUS',
    SEX = 'SEX',
    YES_NO = 'YES_NO',
    YES_NO_NA = 'YES_NO_NA',
}

export enum CatalogueStateEnum {
    ENABLED = 'enabled',
    DISABLED = 'disabled',
}

export enum CatalogueInspectionsStateEnum {
    autogenerated_1 = 'autogenerated_1',
    autogenerated_2 = 'autogenerated_2',
    requested = 'requested',
    scheduled = 'scheduled',
    confirmed = 'confirmed',
    rescheduled_1 = 'rescheduled_1',
    rescheduled_2 = 'rescheduled_2',
}

export enum CatalogueProcessesTypeEnum {
    registration = 'registration',
    update = 'update',
    inactivation = 'inactivation',
    new_classification = 'new_classification',
    new_activity = 'new_activity',
    readmission = 'readmission',
    reclassification = 'reclassification',
    recategorization = 'recategorization',
}

export enum CatalogueProcessesStateEnum {
    pending_1 = 'pending_1',
    pending_2 = 'pending_2',
    completed = 'completed',
}

export enum CatalogueActivitiesCodeEnum {
    agency_continent = 'agency_continent',
    agency_galapagos = 'agency_galapagos',
}

export enum CatalogueCadastresStateEnum {
    pending = 'pending',
    ratified = 'ratified',
    inactive = 'inactive',
    temporary_suspension = 'temporary_suspension',
    definitive_suspension = 'definitive_suspension',
    recategorized = 'recategorized',
    reclassified = 'reclassified',
}

export enum CatalogueSchoolPeriodStateEnum {
    OPEN = 'open',
    CLOSE = 'close',
}

export enum CatalogueSchoolPeriodTypeEnum {
    ORDINARY = 'ordinary',
    EXTRAORDINARY = 'extraordinary',
    ESPECIAL = 'especial',
}

export enum CatalogueSubjectRequirementTypeEnum {
    PREREQUISITE = 'prerequisite',
    CO_REQUISITE = 'co_requisite',
}

export enum CatalogueCareersModalityEnum {
    ON_SITE = 'on-site',
    SEMI_ON_SITE = 'semi-on-site',
    DISTANCE = 'distance',
    DUAL = 'dual',
    ONLINE = 'online',
    HYBRID = 'hybrid',
}

export enum CatalogueYesNoEnum {
    YES = '1',
    NO = '2',
}

export enum UsersIdentificationTypeStateEnum {
    IDENTIFICATION = '1',
    PASSPORT = '2',
}

export enum CatalogueMaritalStatusEnum {
    SINGLE = 'single',
    MARRIED = 'married',
    WIDOWER = 'widower',
    DIVORCED = 'divorced',
    FREE_UNION = 'free_union',
}

export enum CatalogueEthnicOriginEnum {
    INDIGENOUS = 'indigenous',
    AFRO_ECUADORIAN = 'afro_ecuadorian',
    MONTUBIO = 'montubio',
    HALF_BLOOD = 'half_blood',
    WHITE = 'white',
}

export enum CatalogueTypeSchoolEnum {
    FISCAL = 'fiscal',
    FISCOMISIONAL = 'fiscomisional',
    PARTICULAR = 'particular',
    MUNICIPAL = 'municipal',
}

export enum CatalogueStudentLiveEnum {
    ALONE = 'alone',
    BOTH_PARENTS = 'both_parents',
    MOTHER = 'mother',
    FATHER = 'father',
    SPOUSE = 'spouse',
    GRANDPARENTS = 'grandparents',
    OTHER = 'other',
}

export enum CatalogueEconomicContributionEnum {
    PARENTS = 'parents',
    GRAND_PARENTS = 'grand_parents',
    FAMILY = 'family',
    OWN_SALARY = 'own_salary',
    OTHER = 'other',
}
